# Generated by Django 5.2.16 on 2026-07-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('code_cellule', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code Cellule')),
                ('nom_cellule', models.CharField(max_length=200, verbose_name='Nom de la Cellule')),
                ('quartier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quartier')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Cellule',
                'verbose_name_plural': 'Cellules',
                'db_table': 'cellules',
                'ordering': ['code_cellule'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=200, verbose_name='Utilisateur')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_heure', models.DateTimeField(auto_now_add=True, verbose_name='Date & Heure')),
            ],
            options={
                'verbose_name': "Historique d'Activité",
                'verbose_name_plural': 'Historique des Activités',
                'db_table': 'historique_activites',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code_section', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code Section')),
                ('nom_section', models.CharField(max_length=200, verbose_name='Nom de la Section')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
                'ordering': ['code_section'],
            },
        ),
        migrations.CreateModel(
            name='Militant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_militant', models.CharField(max_length=50, unique=True, verbose_name='Code Militant')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenoms', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénom(s)')),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, null=True, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de Naissance')),
                ('num_cni', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° CNI')),
                ('num_carte_electeur', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Carte Électeur')),
                ('lieu_vote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de Vote')),
                ('bureau_vote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bureau de Vote')),
                ('telephone_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('quartier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quartier')),
                ('profession', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession')),
                ('date_adhesion', models.DateField(blank=True, null=True, verbose_name="Date d'Adhésion")),
                ('responsable_recensement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable Recensement')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('cellule', models.ForeignKey(blank=True, db_column='code_cellule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='militants', to='militants.cellule', verbose_name='Cellule')),
                ('section', models.ForeignKey(blank=True, db_column='code_section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='militants', to='militants.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Militant',
                'verbose_name_plural': 'Militants',
                'db_table': 'militants',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='cellule',
            name='section',
            field=models.ForeignKey(db_column='code_section', on_delete=django.db.models.deletion.CASCADE, related_name='cellules', to='militants.section', verbose_name='Section'),
        ),
    ]
