# Generated by Django 5.2.16 on 2026-07-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellule',
            name='code_cellule',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Code Cellule'),
        ),
        migrations.AlterField(
            model_name='militant',
            name='code_militant',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code Militant'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code_section',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Code Section'),
        ),
    ]
